### ISSUE TITLE
fails to build with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [haskell/fgl#110]
```
       Building library for fgl-5.8.0.0..                                                                                           
       [11 of 29] Compiling Data.Graph.Inductive.PatriciaTree                                                                       
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/fgl-5.8.0.0-88e6fadb03c176bd0359c325a9b7007b79065fadce063c2289640306e6b3599a/Data/Grap
h/Inductive/PatriciaTree.hs:138:10: error: [GHC-39999]                                                                              
           • No instance for ‘Functor (Gr a)’                                                                                       
               arising from the head of a quantified constraint
               arising from the superclasses of an instance declaration                                                             
           • In the instance declaration for ‘Bifunctor Gr’                                                                         
           |                                                                                                                        
       138 | instance Bifunctor Gr where                                                                                            
           |          ^^^^^^^^^^^^                                                                                                  
       [27 of 29] Compiling Data.Graph.Inductive.Tree                                                                               
                                                                  
       /var/stackage/work/unpack-dir/unpacked/fgl-5.8.0.0-88e6fadb03c176bd0359c325a9b7007b79065fadce063c2289640306e6b3599a/Data/Grap
h/Inductive/Tree.hs:139:10: error: [GHC-39999]                                                                                      
           • No instance for ‘Functor (Gr a)’                                                                                       
               arising from the head of a quantified constraint                                                                     
               arising from the superclasses of an instance declaration                                                             
           • In the instance declaration for ‘Bifunctor Gr’                                                                         
           |                                                                                                                        
       139 | instance Bifunctor Gr where                          
           |          ^^^^^^^^^^^^
```

**Comment by athas** [comment]
This looks easy to fix.  I will do so and add GHC 9.6 to CI.

**Comment by athas** [comment]
Wait, didn't we fix this already?  You're building fgl-5.8.0.0, which is not the newest version.

**Comment by athas** [comment]
The latest release works fine, and GHC 9.6 is now also used in CI.
